runtime: python311

entrypoint: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT

env_variables:
  GOOGLE_CLOUD_PROJECT: nodal-fountain-470717-j1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6